### PR TITLE
STM8

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Work in progress.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
@TG9541 I was considering to use X or Y as a TOS register, but I see your stm8ef doesn't.  Did you decide against that?

**Comment by TG9541** [comment]
Dr. C.H. Ting decided not to do that - I was a total Forth beginner when I started working on the code. There are indications that the basis for STM8EF was WHYP for the HC11 which has a similar register set.
However, I took some effort to use Y or A as TOS for mixing Forth code with assembly.
You'll find that STM8 16 bit operations and addressing modes leave a lot to wish for. In order to take advantage of these it'a sometimes necessary to make values do a little dance between X, Y, and temporary  storage. STM8EF is, however, heavily size optimized, and fully reentrant (unlike the original code). Speed optimized code would require different coding techniques .

EDIT: [6812ef](http://www.forth.org/library/eforth_SOC/eforth_SOC_source/eForth2/6812EF.ZIP) is the eForth Dr.Ting used as a starting point for the [original STM8EF](https://gist.github.com/deliium/12440fdabfe48fcb31cc).

**Comment by larsbrinkhoff** [comment]
I'll add your uCsim link here for reference:  
https://github.com/TG9541/stm8ef/wiki/STM8S-Programming#sdcc-the-simulator-ucsim

**Comment by larsbrinkhoff** [comment]
> You'll find that STM8 16 bit operations and addressing modes leave a lot to wish for.

Yes, I see that now.  It seems that any optimization I attempt is just out of reach due to missing adressing modes, registers, or instructions.

**Comment by larsbrinkhoff** [comment]
The STM8 port now successfully passes the test in uCsim.

**Pull request merged**
